import 'package:flutter/material.dart';

import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_text_styles.dart';

/// App version shown below — keep this in sync with the `version:` line
/// in pubspec.yaml when you bump it for a release. Deliberately not using
/// a package like package_info_plus here just to avoid one more
/// dependency for a single static string.
const String _appVersion = '1.0.0';

class AboutScreen extends StatelessWidget {
  const AboutScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('About AstroMitra')),
      body: SafeArea(
        child: ListView(
          padding: const EdgeInsets.fromLTRB(20, 16, 20, 32),
          children: [
            Center(
              child: ClipRRect(
                borderRadius: BorderRadius.circular(18),
                child: Image.asset(
                  'assets/astro-icon.png',
                  width: 80,
                  height: 80,
                  fit: BoxFit.cover,
                ),
              ),
            ),
            const SizedBox(height: 16),
            const Center(child: Text('AstroMitra', style: AppTextStyles.displayMedium)),
            const SizedBox(height: 4),
            const Center(child: Text('Version $_appVersion', style: AppTextStyles.caption)),
            const SizedBox(height: 24),
            const Text(
              'AstroMitra calculates your Vedic (sidereal) birth chart — Ascendant, planetary positions, '
              'Rashi, Nakshatra, and houses — using precise astronomical calculations, and lets you ask '
              'questions about your chart through Astro Chat, grounded in your birth details and current '
              'planetary transits.',
              style: AppTextStyles.body,
            ),
            const SizedBox(height: 16),
            const Text(
              'All astrological calculations are performed by the AstroMitra backend using the Swiss '
              'Ephemeris astronomical calculation library. Astro Chat answers are generated by AI, '
              'informed by your calculated chart — the AI never invents or alters a planetary position.',
              style: AppTextStyles.bodySecondary,
            ),
            const SizedBox(height: 24),
            Container(
              padding: const EdgeInsets.all(14),
              decoration: BoxDecoration(color: AppColors.surface, borderRadius: BorderRadius.circular(12)),
              child: const Text(
                'AstroMitra is for reflection and entertainment. It is not a substitute for professional '
                'advice.',
                style: AppTextStyles.caption,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
