import 'package:flutter/material.dart';

import '../../../core/theme/app_colors.dart';
import 'legal_scaffold.dart';

/// Same disclaimer as privacy_policy_screen.dart applies here — original
/// draft copy, not a finished legal document.
class TermsScreen extends StatelessWidget {
  const TermsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return LegalScreenScaffold(
      title: 'Terms of Service',
      children: const [
        _DraftNotice(),
        LegalParagraph('Last updated: [add date before publishing]'),
        LegalHeading('Astrology is for reflection, not certainty'),
        LegalParagraph(
          'AstroMitra provides Vedic astrology calculations and AI-generated interpretations for '
          'entertainment and personal reflection. It is not a substitute for professional medical, legal, '
          'financial, or psychological advice, and nothing in this app should be treated as a guarantee '
          'about future events.',
        ),
        LegalHeading('Accuracy of calculations'),
        LegalParagraph(
          'Birth chart calculations depend on the birth date, time, and place you provide. If your time of '
          'birth is unknown or approximate, your Ascendant and house placements may be less precise \u2014 '
          'this is flagged clearly wherever it applies. Location matching depends on a third-party '
          'geocoding service and may occasionally be imprecise for ambiguous place names.',
        ),
        LegalHeading('Astro Chat and AI-generated answers'),
        LegalParagraph(
          'Answers in Astro Chat are generated by third-party AI models based on your chart data and '
          'question. They may occasionally be inaccurate, incomplete, or not reflect traditional Vedic '
          'astrology consensus perfectly. Use your own judgment.',
        ),
        LegalHeading('Credits and the daily bonus'),
        LegalParagraph(
          'Each Kundli receives a daily allowance of chat questions, which resets once every 24 hours. '
          'After that allowance is used, you may unlock a limited number of additional questions by '
          'watching a rewarded advertisement, available once per day. Credit balances and allowances are '
          'determined and enforced by the AstroMitra backend and may change over time.',
        ),
        LegalHeading('No account, your responsibility to keep your Kundli ID'),
        LegalParagraph(
          'This app has no login system. Your Kundli is referenced by an identifier stored only on your '
          'device. If you uninstall the app, clear its storage, or delete your Kundli from Settings, that '
          'reference is lost and cannot be recovered through the app.',
        ),
        LegalHeading('Changes'),
        LegalParagraph('These terms may be updated from time to time. [Describe your notice process here.]'),
        LegalHeading('Contact'),
        LegalParagraph('[Add your support email or contact method before publishing.]'),
      ],
    );
  }
}

class _DraftNotice extends StatelessWidget {
  const _DraftNotice();

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.only(bottom: 10),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(color: AppColors.warningBg, borderRadius: BorderRadius.circular(10)),
      child: const Text(
        'Draft template — have this reviewed by a lawyer and filled in with your real details before '
        'publishing to the Play Store.',
        style: TextStyle(color: AppColors.warning, fontSize: 12, height: 1.4),
      ),
    );
  }
}
